# Generated by Django 3.0.8 on 2021-02-10 06:09

from django.db import migrations, models
from django.db.migrations.operations.fields import RenameField


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='body'
        ),

    ]
