# Generated by Django 3.2.3 on 2021-08-11 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210811_2208'),
        ('blog', '0007_auto_20210811_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='production_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='portfolio.project'),
            preserve_default=False,
        ),
    ]
