# Generated by Django 3.2.3 on 2021-08-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210811_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='url_blogpost',
        ),
        migrations.AddField(
            model_name='project',
            name='url_production',
            field=models.URLField(blank=True),
        ),
    ]
