# Generated by Django 3.2.7 on 2022-03-18 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_abstract'),
        ('portfolio', '0007_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='active_popper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
        migrations.AddField(
            model_name='tag',
            name='summary',
            field=models.TextField(default='Working on it...', max_length=320),
        ),
        migrations.AddField(
            model_name='tag',
            name='url_post',
            field=models.URLField(blank=True),
        ),
    ]
