name: Django CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        source /home/pkudlanov/environments/personal_portfolio_env/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        deactivate
    - name: Run migrations
      run: |
        source /home/pkudlanov/environments/personal_portfolio_env/bin/activate
        python manage.py migrate
        deactivate
    - name: Restart Gunicorn process
      run: |
        sudo systemctl restart gunicorn
