name: Django CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
<<<<<<< HEAD
        source /home/pkudlanov/actions-runner/personal-portfolio-work/personal-portfolio-django/personal-portfolio-django/env/bin/activate
=======
        source /home/pkudlanov/actions-runner/_work/personal-portfolio-django/personal-portfolio-django/env/bin/activate
>>>>>>> d9c269166e18e4806592f059e3b7c34aa65c43c2
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        deactivate
    - name: Run migrations
      run: |
<<<<<<< HEAD
        source /home/pkudlanov/actions-runner/personal-portfolio-work/personal-portfolio-django/personal-portfolio-django/env/bin/activate
=======
        source /home/pkudlanov/actions-runner/_work/personal-portfolio-django/personal-portfolio-django/env/bin/activate
>>>>>>> d9c269166e18e4806592f059e3b7c34aa65c43c2
        python manage.py migrate
        deactivate
    - name: Restart Gunicorn process
      run: |
        sudo systemctl restart gunicorn
